Added Mask Detection for both laptop and external camera
Avdhesh-Varshney/Jarvis pull request #104
Opened 2024-07-19 10:00 UTC by ChiragGupta16

Closes: #65 
- **Title** : Added Mask Detection for both laptop and external camera
- **Name:**  Chirag Gupta
- **Idenitfy yourself:**  Contributor SSoC

### Describe the add-ons or changes you've made 📃

Give a clear description of what have you added or modifications made

Added the real time mask detection feature  for both laptop and external camera.

### Type of change ☑️

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### How Has This Been Tested? ⚙️

I verified it by testing it myself

### Checklist: ☑️

- [x ] My code follows the [Contributing Guidelines](https://github.com/Avdhesh-Varshney/Jarvis/blob/main/Contributing.md) & [Code of Conduct](https://github.com/Avdhesh-Varshney/Jarvis/blob/main/CODE_OF_CONDUCT.md) of this project.
- [x ] This PR does not contain plagiarized content.
- [x ] I have performed a self-review of my own code.
- [x ] I have commented my code, particularly wherever it was hard to understand.
- [x ] My changes generate no new warnings.

### Screenshots 📷

https://github.com/user-attachments/assets/434152c4-c228-4c98-81eb-799ca2c3626e

### Note to reviewers 📄

2024-07-21 04:18 UTC, Avdhesh-Varshney requested changes
LGTM.

2024-07-21 04:18 UTC, Avdhesh-Varshney commented on temp.jpg
Remove it. Not required.

2024-07-21 06:16 UTC, ChiragGupta16 commented
Thanks for spotting it out.
Did the required changes.

2024-07-22 05:20 UTC, Avdhesh-Varshney approved these changes

2024-07-22 05:21 UTC, merged