added snake game
Avdhesh-Varshney/Jarvis pull request #116
Opened 2024-10-02 12:06 UTC by ShrishtiSingh26

Closes: Issue #112 

- **Title**:  adding a snake game under games section #112
- **Your Name**: Shrishti Singh
- **Idenitfy yourself**:  Contributor in gssoc-ext and Hacktoberfest

### Describe the add-ons or changes you've made 📃

Give a clear description of what have you added or modifications made
Key Points:
Game State Management: All the game state (snake, food, direction, etc.) is stored in st.session_state to persist across user actions.
Grid Display: The game grid is displayed using emojis (🟩 for the snake and 🍎 for the food), but you can customize this.
Movement Control: The player controls the snake with W, A, S, D keys via Streamlit buttons.
Game Logic: The snake moves, eats food, grows, and checks for collisions with walls or itself.
Restart Option: A restart button re-initializes the game state.

### Checklist: ☑️

- [x] My code follows the [Contributing Guidelines](https://github.com/Avdhesh-Varshney/Jarvis/blob/main/Contributing.md) & [Code of Conduct](https://github.com/Avdhesh-Varshney/Jarvis/blob/main/CODE_OF_CONDUCT.md) of this project.
- [x] This PR does not contain plagiarized content.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] My changes generate no new warnings.

### Screenshots 📷

![image](https://github.com/user-attachments/assets/c178f430-fde0-43ce-a694-dcb424ddf460)
![image](https://github.com/user-attachments/assets/69284138-ef78-4bb3-8712-d6eb996d5f4c)

2024-10-02 18:12 UTC, Avdhesh-Varshney requested changes
Never create your pr by committing in `main` branch.

2024-10-02 18:12 UTC, Avdhesh-Varshney commented on src/apps/pages/programs/Games/snakegame.py
> +def snake_game():
There are few changes required.
- rename your file from `snakegame.py` to `snakeGame.py` as mentioned in guidelines.
- snake_game() should have same name as of file name i.e., `snakeGame` after correction.

2024-10-02 18:12 UTC, Avdhesh-Varshney commented on src/apps/pages/programs/Games/snakegame.py
> +snake_game()
Don't call the function here. Because it is this file is automatically executed with the same name as of file name.

2024-10-02 18:37 UTC, ShrishtiSingh26 commented on src/apps/pages/programs/Games/snakegame.py
> +snake_game()
@Avdhesh-Varshney  please elaborate on this issue..

2024-10-02 18:44 UTC, Avdhesh-Varshney requested changes
Attach a working video.

2024-10-02 18:44 UTC, Avdhesh-Varshney commented on src/apps/pages/programs/Games/snakegame.py
> +def snake_Game():
- Remove underscore.
- Review other python programs.

2024-10-03 20:59 UTC, ShrishtiSingh26 commented
@Avdhesh-Varshney resolved the raised issues in PR #117

2024-10-04 08:54 UTC, closed without merging