Created a Scientific Calculator in a file named scal.py
Avdhesh-Varshney/Jarvis pull request #124
Opened 2024-10-04 13:56 UTC by NikhilJ2005

#81 Issue Number 

📋 Scientific Calculator Feature Enhancement
📝 Summary
This pull request introduces a scientific calculator to the Streamlit app, implementing various mathematical functions, trigonometric calculations, and angle mode toggling. This addition provides users with an intuitive interface for performing scientific computations directly within the app.

🚀 Features Added
Basic Calculator Operations: Addition, subtraction, multiplication, and division using intuitive symbols (e.g., ×, ÷).
Scientific Functions:
Trigonometric functions (sin, cos, tan), which adapt to the current angle mode (Degree/Radian).
Exponentiation (^), logarithmic functions (log, ln), square root (√), and the mathematical constants (π, e).
Angle Mode Toggle: Switch between Degree and Radian modes for trigonometric calculations.
Expression Display: Dynamically displays the current input expression and result in the display box.
Utility Buttons:
AC: Clears the entire expression.
DC: Deletes the last character in the expression.
Mode: Toggles between Degree and Radian modes.
Equals (=): Evaluates the current expression using a safe evaluation method.
Automatic Multiplication Insertion: Automatically inserts a multiplication symbol when needed, such as before parentheses or mathematical constants (π, e).
🛠️ Implementation Details
Session State Management: Utilizes Streamlit's session state to keep track of the current expression, display content, and angle mode.
Mathematical Expression Parsing: Implements a safe_dict with custom trigonometric functions to safely evaluate the input using Python's eval function.
Button Layout: Organizes calculator buttons using Streamlit's columns for a grid-like appearance, with specific functionality mapped to each button.
🎨 Adjustments
Adjusted symbols to prevent potential Markdown parsing issues.
Improved user interface to intuitively represent scientific calculator functions.
🔍 Testing
Validated button interactions for basic arithmetic operations.
Tested trigonometric calculations in both Degree and Radian modes.
Ensured that the display updates correctly upon expression evaluation, clearing, and character deletion.

![WhatsApp Image 2024-10-04 at 7 11 26 PM](https://github.com/user-attachments/assets/eceda670-4461-48f5-a4a1-fb56978207c1)
![WhatsApp Image 2024-10-04 at 7 11 26 PM (1)](https://github.com/user-attachments/assets/920efe39-297c-47fd-8bb2-059ee1924702)
![WhatsApp Image 2024-10-04 at 7 11 20 PM](https://github.com/user-attachments/assets/b7f1f5a6-9578-4ebe-b823-fc25305ca070)
![WhatsApp Image 2024-10-04 at 7 11 13 PM](https://github.com/user-attachments/assets/9c422261-2e47-4163-a126-3a112d256c87)

2024-10-05 12:26 UTC, jaidh01 commented
Hey @NikhilJ2005, does your project run properly with the streamlit application?

2024-10-06 09:45 UTC, Avdhesh-Varshney requested changes
Follow the guidelines and attach a full screen working video.

2024-10-07 02:45 UTC, NikhilJ2005 commented
https://youtu.be/nSQAcrjB2qk?si=_YYjtDTMSN2w9Dnz

Is this enough?.

2024-10-07 10:52 UTC, Avdhesh-Varshney commented
I want to show your calculator whether it is properly integrated with the jarvis or not. So, prepare a video from login upto 2-3 test cases on calculator. That's enough

2024-10-12 09:31 UTC, NikhilJ2005 commented
https://youtu.be/nCZ0ZDUnjt0?si=_FAkCu05RBNBbpla. Done

2024-10-12 09:39 UTC, Avdhesh-Varshney requested changes
Follow the guidelines

2024-10-12 09:39 UTC, Avdhesh-Varshney commented on src/utils/functions.py
Undo these changes.

2024-10-12 09:39 UTC, Avdhesh-Varshney commented on scal.py
Keep this file in [`StudyPrograms`](https://github.com/Avdhesh-Varshney/Jarvis/tree/main/src/apps/pages/programs/StudyPrograms) folder by renaming to `scientificCalculator`

2024-10-12 10:07 UTC, NikhilJ2005 commented
okay

2024-10-19 14:38 UTC, Avdhesh-Varshney commented
What's the update?

2024-10-19 15:20 UTC, NikhilJ2005 commented
Can you assign some one else for this issue , since semester exam has started too much busy.

2024-10-19 15:57 UTC, closed without merging