Recipe_finder addition
Avdhesh-Varshney/Jarvis pull request #134
Opened 2024-10-06 10:33 UTC by shrehs

Closes: 

- **Title**:   Recipe Finder
- **Your Name**:  Shreya H S
- **Idenitfy yourself**:  GSSOC-Ext'24

### Describe the add-ons or changes you've made 📃

Give a clear description of what have you added or modifications made
Flexbox Layout: Implemented a flexbox layout to organize the recipe items in a responsive manner. Each recipe item is displayed in a flexible container, allowing for better alignment and spacing without altering the size or shape of the elements.

Clickable Recipe Items: Modified the recipe item layout so that the entire item is clickable, not just the title. This enhances user experience by making it easier to navigate to the recipe details.

Title Style Adjustments: Removed the default blue color and underline from the recipe title links on hover, ensuring a cleaner appearance that matches your design preferences. This was achieved by adding specific CSS styles.

Input Placeholder Text: Added placeholder text inside the input box to guide users on what to enter (e.g., “Enter ingredients or dish name”), which disappears when the user clicks on the input field.

Title and more formating: Adjusted the font size of the recipe titles for better readability, making them more prominent without changing their color or style drastically.

Git Ignore File: Guided on creating a .gitignore file to prevent sensitive information, such as API keys, virtual enve from being pushed to the repository.

### Checklist: ☑️

- [x] My code follows the [Contributing Guidelines](https://github.com/Avdhesh-Varshney/Jarvis/blob/main/Contributing.md) & [Code of Conduct](https://github.com/Avdhesh-Varshney/Jarvis/blob/main/CODE_OF_CONDUCT.md) of this project.
- [x] This PR does not contain plagiarized content.
- [x ] I have performed a self-review of my own code.
- [ x] I have commented my code, particularly wherever it was hard to understand.
- [x ] My changes generate no new warnings.

### Screenshots 📷

![Screenshot (131)](https://github.com/user-attachments/assets/44a56074-9dad-43d1-8b02-6ef04ca53092)
![Screenshot (132)](https://github.com/user-attachments/assets/a4404817-cb50-4f9d-bece-2e0373e54b55)
![Screenshot (133)](https://github.com/user-attachments/assets/25750c01-a7fb-4e7f-bf68-f49d6f33d496)

2024-10-07 10:59 UTC, Avdhesh-Varshney requested changes
Follow the naming conventions and read guidelines.

2024-10-07 10:59 UTC, Avdhesh-Varshney commented on src/apps/pages/programs/ApiPrograms/recipe_finder/recipe_finder.py
> +    api_key = os.getenv('SPOONACULAR_API_KEY')  # Retrieve API key from environment variable
Use streamlit secrets to store these environment variables. Don't use `os.getenv`.

2024-10-07 10:59 UTC, Avdhesh-Varshney commented on .gitignore
Undo these changes.

2024-10-07 10:59 UTC, Avdhesh-Varshney commented on src/apps/pages/programs/ApiPrograms/recipe_finder/.gitignore
delete it

2024-10-07 11:31 UTC, shrehs commented on src/apps/pages/programs/ApiPrograms/recipe_finder/recipe_finder.py
> +    api_key = os.getenv('SPOONACULAR_API_KEY')  # Retrieve API key from environment variable
I'll do the required changes and get back to you.

2024-10-11 15:29 UTC, closed without merging

2024-10-11 15:54 UTC, shrehs commented on src/apps/pages/programs/ApiPrograms/recipe_finder/.gitignore
Hey,
Hope this finds you well. I have opened #172 PR for the First Review requested changes. Please do let me know if it requires further changes. Thank you.