Text Summarization NLP
Avdhesh-Varshney/Jarvis pull request #156
Opened 2024-10-08 18:59 UTC by Peart-Guy

Closes: #64 

- **Title**: Text Summarization using NLP
- **Your Name**: Ankan
- **Idenitfy yourself**: GSSOC-24 EXTD

### Describe the add-ons or changes you've made 📃
It is Text Summarization Model built using NLP which helps user to summarize long texts. The user just needs to type
the Passage they want and click summarize and within few seconds the model does the job. It has a very suitable UI.

This Model is a Natural Language Processing (NLP) model to summarize long pieces of text into concise summaries
The Backend of the project is built in Python using NLP model Transformer and the frontend is built with Streamlit . The Backend and front is connected with Streamlit in python

### Checklist: ☑️

- [x] My code follows the [Contributing Guidelines](https://github.com/Avdhesh-Varshney/Jarvis/blob/main/Contributing.md) & [Code of Conduct](https://github.com/Avdhesh-Varshney/Jarvis/blob/main/CODE_OF_CONDUCT.md) of this project.
- [x] This PR does not contain plagiarized content.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] My changes generate no new warnings.

### Screenshots 📷
![Screenshot 2024-10-09 001741](https://github.com/user-attachments/assets/e2798e61-3f40-443b-8e96-8a243cc92390)

https://github.com/user-attachments/assets/ec30545d-3154-440e-a21c-85fb49884e59

2024-10-08 19:08 UTC, Peart-Guy commented
I have built the newer version with streamlit app as per the requirements ,henceforth creating this new pull request. 
I hope everything is fine . @Avdhesh-Varshney

2024-10-09 15:07 UTC, Avdhesh-Varshney requested changes

2024-10-09 15:07 UTC, Avdhesh-Varshney commented on src/apps/pages/models/ChatBotModels/text_summarry2/README.md
delete this readme file

2024-10-09 15:07 UTC, Avdhesh-Varshney commented on src/apps/pages/models/ChatBotModels/text_summarry2/TextSummary.py
Follow the naming convention and compile all the function in 1 py function as file name as mentioned in guidelines. Attach the video from login upto the program testing.

2024-10-09 15:08 UTC, Avdhesh-Varshney commented on src/apps/pages/models/ChatBotModels/text_summarry2/TextSummary.py
Use atleast 3 test cases.

2024-10-10 10:49 UTC, Peart-Guy commented
I have commited all the changes as per the rules. I think everything is fine now @Avdhesh-Varshney

2024-10-10 16:57 UTC, Avdhesh-Varshney commented on src/apps/pages/models/ChatBotModels/text_summarry2/TextSummary.py
video?

2024-10-10 18:30 UTC, Peart-Guy commented on src/apps/pages/models/ChatBotModels/text_summarry2/TextSummary.py
> All those credentials cannot be provided because of confidentiality and attach a video as mentioned above. You can join the discord or github discussion for it.

Can you please provide the discord link ...

2024-10-11 05:11 UTC, Avdhesh-Varshney commented on src/apps/pages/models/ChatBotModels/text_summarry2/TextSummary.py
![image](https://github.com/user-attachments/assets/dc02aa6f-e336-4bea-99b7-234595faeaad)

https://discord.gg/tSqtvHUJzE

2024-10-15 17:05 UTC, Peart-Guy commented on src/apps/pages/models/ChatBotModels/text_summarry2/TextSummary.py
> Use atleast 3 test cases.
@Avdhesh-Varshney 

I have done all the changes  like the file and folder name changed and also attaching the video reference  of 3 cases.
Kindly check it out and Give the Hacktoberfest, GSSOC-24 EXTD

https://github.com/user-attachments/assets/0a4fbfff-66b6-4b9f-acb2-6db54b1974bc

2024-10-16 12:48 UTC, Avdhesh-Varshney requested changes

2024-10-16 12:48 UTC, Avdhesh-Varshney commented on .streamlit/secrets.example.toml
Undo this file

2024-10-16 12:48 UTC, Avdhesh-Varshney commented on src/apps/pages/models/ChatBotModels/TextSummarizationModel/textSummarizationModel.py
> +textSummarizationModel()
Don't call it from your file. It is automatically called up

2024-10-16 12:48 UTC, Avdhesh-Varshney commented on requirements.txt
Resolve conflicts.

2024-10-16 12:49 UTC, Avdhesh-Varshney commented
Don't create a lots of commits, Otherwise it can't be merged into `main` branch

2024-10-16 13:17 UTC, closed without merging

2024-10-16 13:34 UTC, Peart-Guy commented
@Avdhesh-Varshney
  I am closing this PR and will be creating a New fresh Pull Request with 1 perfect commit. I think that will be more clear easy to merge.