Added Password Strength Validation (8 Characters, Special Character, and Digit)
Avdhesh-Varshney/Jarvis pull request #165
Opened 2024-10-10 18:45 UTC by jaidh01

Closes:  #118 

- **Title**:  Added Password Strength Validation (8 Characters, Special Character, and Digit)
- **Your Name**: Jai Dhingra
- **Idenitfy yourself**: GSSOC-extd Contributor, Hacktoberfest

### Describe the add-ons or changes you've made 📃

Added Password strength Validation (8 Characters, Special Character, and Digit).

### Checklist: ☑️

- [x] My code follows the [Contributing Guidelines](https://github.com/Avdhesh-Varshney/Jarvis/blob/main/Contributing.md) & [Code of Conduct](https://github.com/Avdhesh-Varshney/Jarvis/blob/main/CODE_OF_CONDUCT.md) of this project.
- [x] This PR does not contain plagiarized content.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] My changes generate no new warnings.

### Screenshots 📷

https://github.com/user-attachments/assets/653896a8-06da-43f1-8c31-3703b8a94ab6

2024-10-11 05:20 UTC, Avdhesh-Varshney requested changes

2024-10-11 05:20 UTC, Avdhesh-Varshney commented on src/auth/signup.py
Keep the file in 2 space seprated code and commit your code only. It'll be difficult to review the pr

2024-10-11 09:55 UTC, jaidh01 commented on src/auth/signup.py
Sorry for the inconvenience.
I have done all these changes. Please spare a time to look at it.

2024-10-12 08:03 UTC, jaidh01 commented
Hi @Avdhesh-Varshney, I have done all the changes as you suggested.
Please spare a time to look at it.

2024-10-13 16:07 UTC, jaidh01 commented
Hi @Avdhesh-Varshney, Is it good, or some changes should be done?

2024-10-15 14:21 UTC, jaidh01 commented
Hi @Avdhesh-Varshney @Zedoman, Is there anything else I have to do in this?

2024-10-17 17:25 UTC, Zedoman approved these changes

2024-10-19 14:29 UTC, Avdhesh-Varshney approved these changes

2024-10-19 14:29 UTC, Avdhesh-Varshney commented on src/auth/signup.py
You have initialize the function for password validation. But where have you used it?

2024-10-19 14:29 UTC, Avdhesh-Varshney commented on src/auth/signup.py
Yes, You have created this function. But you have not used or called it anywhere?

2024-10-19 14:29 UTC, merged