PDFToolBox
Avdhesh-Varshney/Jarvis pull request #216
Opened 2024-10-31 16:56 UTC by shrehs

Closes: #215 

- **Title**:  Completion of PDFToolbox 
- **Your Name**: Shreya H S
- **Idenitfy yourself**:  GSSOC-Ext, Hacktoberfest

### Describe the add-ons or changes you've made 📃
Implement mergePDF, splitPDF, rotatePDF, encryptPDF, decryptPDF functions

Give a clear description of what have you added or modifications made

### Checklist: ☑️

- [x] My code follows the [Contributing Guidelines](https://github.com/Avdhesh-Varshney/Jarvis/blob/main/Contributing.md) & [Code of Conduct](https://github.com/Avdhesh-Varshney/Jarvis/blob/main/CODE_OF_CONDUCT.md) of this project.
- [x] This PR does not contain plagiarized content.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] My changes generate no new warnings.

### Screenshots 📷

[PDFToolbox1.webm](https://github.com/user-attachments/assets/b22cb462-f538-4f1b-823a-f384d41dc049)
![Screenshot (144)](https://github.com/user-attachments/assets/c8d58d27-c764-4f97-8a63-d0dcd6aec089)
![Screenshot (145)](https://github.com/user-attachments/assets/ea051ace-2b1a-4d62-a548-5912e10a4d9c)

2024-10-31 17:51 UTC, Zedoman commented
Also provide a video for that @shrehs

2024-10-31 17:59 UTC, shrehs commented
> Also provide a video for this @shrehs

I have! It is just above the image (underlined blue font)

2024-10-31 19:43 UTC, Zedoman submitted a review, later dismissed

2024-11-01 06:32 UTC, Avdhesh-Varshney requested changes
Remove these 2 files from your commit

2024-11-01 06:32 UTC, Avdhesh-Varshney commented on src/apps/pages/programs/ApiPrograms/recipe_finder/.gitignore
.

2024-11-01 06:32 UTC, Avdhesh-Varshney commented on src/apps/pages/programs/ApiPrograms/recipe_finder/recipe_finder.py
.

2024-11-01 07:16 UTC, shrehs commented
> Remove these 2 files from your commit

Done

2024-11-01 11:26 UTC, Avdhesh-Varshney approved these changes

2024-11-01 16:39 UTC, Zedoman approved these changes

2024-11-01 16:39 UTC, merged