new feat : password_generator in casual programs
Avdhesh-Varshney/Jarvis pull request #57
Opened 2024-06-27 22:25 UTC by akarshghildyal

Closes: Password Generator Program #53

- **Title** : Password Generator Program
- **Name:** Akarsh Ghildyal
- **Idenitfy yourself:** SSOC Contributor

### Describe the add-ons or changes you've made 📃
Made a password generator program using python, streamlit.
Give a clear description of what have you added or modifications made
Created a password generator that has option to have uppercase, lowercase, digits and special characters. User can choose at-least anyone and at-max all the options. The user also has the option of determining the length of the password, from 6-24 characters, default is set to 12. Copy to clipboard button is also available to directly copy the generated password, instead of selecting the entire text and copying it manually. This reduces the friction and enhances user experience.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### How Has This Been Tested? ⚙️

I have tested the changes in my local machine.

### Checklist: ☑️

- [x] My code follows the [Contributing Guidelines](https://github.com/Avdhesh-Varshney/Jarvis/blob/main/Contributing.md) & [Code of Conduct](https://github.com/Avdhesh-Varshney/Jarvis/blob/main/CODE_OF_CONDUCT.md) of this project.
- [x] This PR does not contain plagiarized content.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] My changes generate no new warnings.

### Screenshots 📷

https://github.com/Avdhesh-Varshney/Jarvis/assets/129004417/dd38bb91-fdb7-40f5-a006-07425c0413b9

![image](https://github.com/Avdhesh-Varshney/Jarvis/assets/129004417/c619a7f6-bb31-41ce-aff6-fd64c732ad36)

![image](https://github.com/Avdhesh-Varshney/Jarvis/assets/129004417/ca6422ce-8d72-47fa-a422-b5ea26fe143a)

![image](https://github.com/Avdhesh-Varshney/Jarvis/assets/129004417/a26acf45-5ef4-4bbf-b6ad-a206b034a1f9)

### Note to reviewers 📄

None.

2024-06-28 04:03 UTC, Avdhesh-Varshney requested changes
@akarshghildyal looks great but don't keep it in sidebar keep everything in the main page.
Then re-attach a working video.

2024-06-28 08:06 UTC, akarshghildyal commented
@Avdhesh-Varshney Okay, will get it done by tonight.

2024-06-28 10:03 UTC, akarshghildyal commented
@Avdhesh-Varshney I have updated it as per your review. Kindly see the video for reference.

https://github.com/Avdhesh-Varshney/Jarvis/assets/129004417/17081a21-55e6-44be-8f58-777d052d35c1

2024-06-28 16:42 UTC, Avdhesh-Varshney requested changes

2024-06-28 16:42 UTC, Avdhesh-Varshney commented on src/apps/pages/programs/CasualPrograms/password_generator.py
@akarshghildyal 
- solve it without `session_state`s. This will increase the caching of the app.
- Use simple form input and get the data. 
- In place of slider for length of password, get the numerical input above `4`.

2024-06-29 07:47 UTC, Avdhesh-Varshney approved these changes
@akarshghildyal PR Approved 🎉

But for the next time, raise your pr in the seprate branch not committed in main branch.

2024-06-29 07:47 UTC, merged