Facts API program
Avdhesh-Varshney/Jarvis pull request #86
Opened 2024-07-01 03:37 UTC by kom-senapati

Closes: #76 

- **Title** : 
- **Name:** K Om Senapati
- **Idenitfy yourself:** SSOC

### Describe the add-ons or changes you've made 📃

Added a facts program using a free API https://uselessfacts.jsph.pl/api/v2/facts/random
Selecting Facts under dropdown shows a random fact and Jarvis also speaks it.

### Type of change ☑️

What sort of change have you made:

- [X] New feature (non-breaking change which adds functionality)

### How Has This Been Tested? ⚙️

Selected the API program from dropdown many times and it gave a random fact each time.

### Checklist: ☑️

- [X] My code follows the [Contributing Guidelines](https://github.com/Avdhesh-Varshney/Jarvis/blob/main/Contributing.md) & [Code of Conduct](https://github.com/Avdhesh-Varshney/Jarvis/blob/main/CODE_OF_CONDUCT.md) of this project.
- [X] This PR does not contain plagiarized content.
- [X] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly wherever it was hard to understand.
- [X] My changes generate no new warnings.

### Screenshots 📷

![image](https://github.com/Avdhesh-Varshney/Jarvis/assets/92045934/4fe05582-6332-492f-b9d7-9b9e2891e0e3)

2024-07-02 15:11 UTC, Avdhesh-Varshney requested changes

2024-07-02 15:11 UTC, Avdhesh-Varshney commented on src/apps/pages/programs/apiProgram.py
Rename `Facts` to `General Facts`

2024-07-02 15:12 UTC, Avdhesh-Varshney commented on src/apps/pages/programs/apiProgram.py
Also add a working video

2024-07-02 16:29 UTC, kom-senapati commented on src/apps/pages/programs/apiProgram.py
Done

2024-07-03 03:37 UTC, Avdhesh-Varshney approved these changes

2024-07-03 03:37 UTC, merged