Added QR Code Generator Program in Jarvis
Avdhesh-Varshney/Jarvis pull request #90
Opened 2024-07-03 06:01 UTC by vishalmaurya850

Closes: 

- **Title** : QR code Generator
- **Name:** 
- **Idenitfy yourself:** 

### Describe the add-ons or changes you've made 📃

I have updated the requirement.txt file and added a qr code generator program integrated in Jarvis

### Type of change ☑️

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### How Has This Been Tested? ⚙️

### Checklist: ☑️

- [ ] My code follows the [Contributing Guidelines](https://github.com/Avdhesh-Varshney/Jarvis/blob/main/Contributing.md) & [Code of Conduct](https://github.com/Avdhesh-Varshney/Jarvis/blob/main/CODE_OF_CONDUCT.md) of this project.
- [ ] This PR does not contain plagiarized content.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly wherever it was hard to understand.
- [ ] My changes generate no new warnings.

### Screenshots 📷

### Note to reviewers 📄

2024-07-03 06:12 UTC, vishalmaurya850 commented
Please merge my PR @Avdhesh-Varshney

2024-07-03 12:31 UTC, vishalmaurya850 reviewed
Merge it

2024-07-04 12:18 UTC, Avdhesh-Varshney requested changes

2024-07-04 12:18 UTC, Avdhesh-Varshney commented on requirements.txt
resolve this error

2024-07-04 12:18 UTC, Avdhesh-Varshney commented on src/apps/pages/programs/ImageGenerators/qr_code_generator.py
> +def main():
rename this main to `qrCodeGenerator()`

2024-07-04 13:30 UTC, vishalmaurya850 commented on requirements.txt
Please attach the error you are getting as there is no error at my side.

2024-07-05 09:03 UTC, Avdhesh-Varshney commented on requirements.txt
attach a working video

2024-07-05 10:43 UTC, vishalmaurya850 commented
Uploading Screen Recording 2024-07-05 155532.mp4…

2024-07-05 11:14 UTC, vishalmaurya850 commented
https://github.com/Avdhesh-Varshney/Jarvis/assets/40622097/e837b959-63ce-43f7-b546-d087a965eb9d

2024-07-05 11:14 UTC, vishalmaurya850 commented
https://github.com/Avdhesh-Varshney/Jarvis/assets/40622097/f299ae8b-0b7a-4222-a845-0ce308538655

2024-07-05 11:21 UTC, Avdhesh-Varshney approved these changes

2024-07-05 11:21 UTC, Avdhesh-Varshney commented
> Screen.Recording.2024-07-05.155846.mp4

@vishalmaurya850 only this video is required not the video for setup of project. And program LGTM.

2024-07-05 11:22 UTC, merged

2024-07-05 11:22 UTC, Avdhesh-Varshney commented
@vishalmaurya850 mention your issue and properly link your issue. Otherwise labels will not attach on merging the pr

2024-07-05 11:38 UTC, vishalmaurya850 commented
Which Issue are you talking about @Avdhesh-Varshney

2024-07-05 12:06 UTC, Avdhesh-Varshney commented
> Which Issue are you talking about @Avdhesh-Varshney

related to this pr. Properly mention your issue number in the pr template while raising not in the comment section after raising the pr.

2024-07-05 12:12 UTC, vishalmaurya850 commented
Ok now it's perfect??